name: code-coverage

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write
  code-quality: write
  pull-requests: write

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -e '.[dev]' coverage

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s hollow_grid/tests -v
          coverage xml -o coverage.xml
          coverage report

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: ./coverage.xml
          language: python
